on:
  push:
    tags:
      - "v*.*.*"

jobs:
  homebrew:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: GitHub
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          body: |
            ## Changelog
